import { useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import type { CheckIn, DayNote, Outcome, RoutineId, Settings, Size } from "./types";
import { dateKey, exportData, hashPin, loadCheckIns, loadNotes, loadSettings, saveCheckIns, saveNotes, saveSettings } from "./storage";
import { deleteCheckIn, loadFamilyData, supabase, syncCheckIns, syncConfigured, syncDayNote } from "./supabase";

const routines:{id:RoutineId;label:string;note:string;icon:string}[]=[
 {id:"breakfast",label:"After breakfast",note:"A bright start",icon:"☀️"},{id:"lunch",label:"After lunch or snack",note:"A cosy pause",icon:"🍎"},{id:"dinner",label:"After dinner",note:"A calm finish",icon:"🌙"}];
const outcomes:{id:Outcome;icon:string;label:string}[]=[{id:"happy",icon:"😊",label:"Poo!"},{id:"neutral",icon:"🙂",label:"A little"},{id:"not-yet",icon:"😌",label:"Not this time"}];
const sizes:{id:Size;label:string;dots:number}[]=[{id:"little",label:"Little",dots:1},{id:"medium",label:"Medium",dots:2},{id:"big",label:"Big",dots:3}];
type Tab="today"|"calendar"|"grownups";

export default function App(){
 const[user,setUser]=useState<User|null>(null),[authReady,setAuthReady]=useState(!syncConfigured);
 useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>{setUser(data.user);setAuthReady(true)});const{data}=supabase.auth.onAuthStateChange((_event,session)=>{setUser(session?.user??null);setAuthReady(true)});return()=>data.subscription.unsubscribe()},[]);
 if(!authReady)return <main className="app-shell"><section className="page pin-page"><div className="lock-art">🌱</div><p className="eyebrow">NOAM’S LITTLE WINS</p><h2>Opening your garden…</h2></section></main>;
 if(syncConfigured&&!user)return <FamilyGate onOpen={setUser}/>;
 if(!syncConfigured&&!import.meta.env.DEV)return <SetupGate/>;
 return <FamilyApp/>;
}

function FamilyGate({onOpen}:{onOpen:(user:User)=>void}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState("");const signIn=async()=>{if(!supabase)return;setMessage("Opening…");const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return setMessage("That sign-in didn’t match. Please try again.");if(data.user)onOpen(data.user)};return <main className="app-shell"><section className="page family-gate"><div className="gate-art">🌻</div><p className="eyebrow">A PRIVATE FAMILY GARDEN</p><h1>Welcome, family</h1><p>Ask a grown-up to open Noam’s little wins on this phone.</p><label>Parent email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary wide" onClick={signIn}>Open our garden</button>{message&&<p className="gate-message" role="status">{message}</p>}<small>Once opened, this family phone stays ready for Noam.</small></section></main>}

function SetupGate(){return <main className="app-shell"><section className="page family-gate"><div className="gate-art">🔐</div><p className="eyebrow">FAMILY SETUP NEEDED</p><h1>This garden is locked</h1><p>The family connection has not been added yet. A grown-up can finish the private setup from the project instructions.</p><small>No toilet-time information can be recorded on this screen.</small></section></main>}

function FamilyApp(){
 const[tab,setTab]=useState<Tab>("today"),[checkIns,setCheckIns]=useState<CheckIn[]>(loadCheckIns),[notes,setNotes]=useState<DayNote[]>(loadNotes),[settings,setSettings]=useState<Settings>(loadSettings),[editing,setEditing]=useState<RoutineId|null>(null),[celebrate,setCelebrate]=useState(false),[parentOpen,setParentOpen]=useState(false),[notice,setNotice]=useState(""),[selectedDate,setSelectedDate]=useState(dateKey());
 const today=dateKey(),selectedCheckIns=checkIns.filter(c=>c.date===selectedDate),stars=checkIns.length,poos=checkIns.filter(c=>c.outcome==="happy"||c.outcome==="neutral").length;
 const streak=useMemo(()=>{const days=new Set(checkIns.map(c=>c.date));let count=0,d=new Date();while(days.has(dateKey(d))){count++;d.setDate(d.getDate()-1)}return count},[checkIns]);
 useEffect(()=>saveCheckIns(checkIns),[checkIns]);useEffect(()=>saveNotes(notes),[notes]);useEffect(()=>saveSettings(settings),[settings]);
 useEffect(()=>{if(!syncConfigured)return;loadFamilyData().then(remote=>{setCheckIns(local=>{const byId=new Map([...remote.checkIns,...local].map(item=>[item.id,item]));return[...byId.values()]});setNotes(local=>{const byDate=new Map([...remote.notes,...local].map(item=>[item.date,item]));return[...byDate.values()]})}).catch(()=>undefined)},[]);
 useEffect(()=>{const retry=()=>{syncCheckIns(checkIns).catch(()=>undefined)};window.addEventListener("online",retry);return()=>window.removeEventListener("online",retry)},[checkIns]);
 const record=(routine:RoutineId,outcome?:Outcome,size?:Size)=>{const existing=checkIns.find(c=>c.date===selectedDate&&c.routine===routine),now=new Date().toISOString();const item:CheckIn=existing?{...existing,outcome,size,updatedAt:now,synced:false}:{id:crypto.randomUUID(),date:selectedDate,routine,outcome,size,createdAt:now,updatedAt:now,synced:false};const next=[...checkIns.filter(c=>c.id!==item.id),item];setCheckIns(next);setEditing(null);setCelebrate(true);setNotice(selectedDate===today?(outcome==="happy"||outcome==="neutral"?"A little win! ⭐":"Brave try! ⭐"):"Past day updated ⭐");setTimeout(()=>setCelebrate(false),1200);syncCheckIns(next).catch(()=>undefined)};
 const remove=(item:CheckIn)=>{const next=checkIns.filter(c=>c.id!==item.id);setCheckIns(next);setEditing(null);setNotice("That try was removed");deleteCheckIn(item.id).catch(()=>setNotice("Removed here; cloud retry needed"))};
 const moveDay=(amount:number)=>{const d=new Date(selectedDate+"T12:00:00");d.setDate(d.getDate()+amount);const next=dateKey(d);if(next<=today){setSelectedDate(next);setEditing(null)}};
 return <main className="app-shell">{celebrate&&<div className="star-burst" aria-hidden="true">⭐</div>}<header className="topbar"><div><p className="eyebrow">NOAM’S LITTLE WINS</p><h1>{tab==="today"?"Hello, sunshine!":tab==="calendar"?"Your bright month":"Grown-ups’ corner"}</h1></div><div className="star-pill" aria-label={`${stars} stars`}><span>⭐</span> {stars}</div></header>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="Close">×</button></div>}
 {tab==="today"&&<Today todays={selectedCheckIns} editing={editing} setEditing={setEditing} record={record} remove={remove} stars={stars} selectedDate={selectedDate} today={today} moveDay={moveDay}/>} {tab==="calendar"&&<Calendar checkIns={checkIns}/>} {tab==="grownups"&&(parentOpen?<Parent checkIns={checkIns} setCheckIns={setCheckIns} notes={notes} setNotes={setNotes} settings={settings} setSettings={setSettings} tries={checkIns.length} poos={poos} streak={streak} onLock={()=>setParentOpen(false)}/>:<PinGate settings={settings} setSettings={setSettings} onOpen={()=>setParentOpen(true)}/>)}
 <nav className="bottom-nav" aria-label="Main navigation"><button className={tab==="today"?"active":""} onClick={()=>setTab("today")}><span>☀️</span>Today</button><button className={tab==="calendar"?"active":""} onClick={()=>setTab("calendar")}><span>🗓️</span>Calendar</button><button className={tab==="grownups"?"active":""} onClick={()=>setTab("grownups")}><span>🔒</span>Grown-ups</button></nav></main>
}

function Today({todays,editing,setEditing,record,remove,stars,selectedDate,today,moveDay}:{todays:CheckIn[];editing:RoutineId|null;setEditing:(id:RoutineId|null)=>void;record:(id:RoutineId,o?:Outcome,s?:Size)=>void;remove:(item:CheckIn)=>void;stars:number;selectedDate:string;today:string;moveDay:(amount:number)=>void}){const isToday=selectedDate===today,dateLabel=isToday?"Today":new Date(selectedDate+"T12:00:00").toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"});return <section className="page today-page"><div className="day-switcher"><button onClick={()=>moveDay(-1)} aria-label="Previous day">‹</button><div><p className="eyebrow">TOILET-TIME DAY</p><h2>{dateLabel}</h2></div><button onClick={()=>moveDay(1)} disabled={isToday} aria-label="Next day">›</button></div><div className="progress-card"><div><span className="tiny-label">PATH TO OCTOBER</span><strong>{stars<10?"Every brave try helps us grow":"Look how your garden is growing!"}</strong></div><div className="path" aria-label={`${stars} little wins collected`}><span className="path-fill" style={{width:`${Math.min(100,(stars%30)/30*100)}%`}}/></div><div className="path-icons"><span>🌱</span><span>🌿</span><span>🌻</span></div></div><div className="section-heading"><div><p className="eyebrow">{isToday?"TODAY’S ROUTINE":"THIS DAY’S ROUTINE"}</p><h2>Three cosy toilet times</h2></div><span>{todays.length}/3</span></div><div className="routine-list">{routines.map(r=>{const done=todays.find(c=>c.routine===r.id);return <article className={`routine-card ${done?"done":""}`} key={r.id}><button className="routine-main" onClick={()=>done?setEditing(r.id):record(r.id)}><span className="routine-icon">{done?"⭐":r.icon}</span><span className="routine-copy"><strong>{r.label}</strong><small>{done?(done.outcome==="not-yet"?"Brave try — nice work!":"Little win collected!"):r.note}</small></span><span className="check">{done?"✓":"+"}</span></button>{editing===r.id&&<CheckInPanel initial={done} onSave={(o,s)=>record(r.id,o,s)} onRemove={done?()=>remove(done):undefined} onCancel={()=>setEditing(null)}/>} {!done&&<button className="add-details" onClick={()=>setEditing(r.id)}>Add a feeling or size <span>›</span></button>}</article>})}</div><div className="collection"><div className="collection-art">{["🌱","🐝","🌼","🦋"].slice(0,Math.max(1,Math.min(4,Math.ceil(stars/3)))).map((x,i)=><span key={i}>{x}</span>)}</div><div><p className="eyebrow">YOUR COLLECTION</p><h3>{stars<4?"A tiny garden begins":"A happy garden is growing"}</h3><p>Every try adds something lovely.</p></div></div></section>}

function CheckInPanel({initial,onSave,onRemove,onCancel}:{initial?:CheckIn;onSave:(o?:Outcome,s?:Size)=>void;onRemove?:()=>void;onCancel:()=>void}){const[outcome,setOutcome]=useState<Outcome|undefined>(initial?.outcome),[size,setSize]=useState<Size|undefined>(initial?.size);return <div className="checkin-panel"><fieldset><legend>How did it feel?</legend><div className="choice-row">{outcomes.map(o=><button type="button" className={outcome===o.id?"selected":""} onClick={()=>setOutcome(outcome===o.id?undefined:o.id)} key={o.id}><span>{o.icon}</span>{o.label}</button>)}</div></fieldset><fieldset><legend>Want to add a size?</legend><div className="choice-row sizes">{sizes.map(s=><button type="button" className={size===s.id?"selected":""} onClick={()=>setSize(size===s.id?undefined:s.id)} key={s.id}><span className="dots">{Array.from({length:s.dots},(_,i)=><i key={i}/>)}</span>{s.label}</button>)}</div></fieldset><div className="panel-actions"><button className="text-button" onClick={onCancel}>Maybe later</button><button className="primary" onClick={()=>onSave(outcome,size)}>Save little win ⭐</button></div>{onRemove&&<button className="remove-try" onClick={onRemove}>Undo this toilet try</button>}</div>}

function Calendar({checkIns}:{checkIns:CheckIn[]}){const now=new Date(),year=now.getFullYear(),month=now.getMonth(),first=new Date(year,month,1),total=new Date(year,month+1,0).getDate(),cells=[...Array(first.getDay()).fill(null),...Array.from({length:total},(_,i)=>i+1)];return <section className="page"><div className="month-card"><div className="month-title"><button aria-label="Previous month">‹</button><div><p className="eyebrow">OUR LITTLE WINS</p><h2>{now.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</h2></div><button aria-label="Next month">›</button></div><div className="weekdays">{"SMTWTFS".split("").map((d,i)=><span key={i}>{d}</span>)}</div><div className="calendar-grid">{cells.map((day,i)=>{const key=day?`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`:"",count=checkIns.filter(c=>c.date===key).length;return <div className={`${day===now.getDate()?"today":""} ${count?"has-win":""}`} key={i}>{day&&<><span>{day}</span>{count>0&&<small>{"★".repeat(count)}</small>}</>}</div>})}</div></div><div className="kind-note"><span>🌈</span><div><strong>Every mark is a brave try</strong><p>Quiet days are part of the journey too.</p></div></div></section>}

function PinGate({settings,setSettings,onOpen}:{settings:Settings;setSettings:(s:Settings)=>void;onOpen:()=>void}){const[pin,setPin]=useState(""),[error,setError]=useState(""),creating=!settings.pinHash;const submit=async()=>{if(pin.length<4)return setError("Please use at least 4 numbers.");const hashed=await hashPin(pin);if(creating){setSettings({...settings,pinHash:hashed});onOpen()}else if(hashed===settings.pinHash)onOpen();else setError("That PIN didn’t match. Try again.")};return <section className="page pin-page"><div className="lock-art">🔐</div><p className="eyebrow">FOR GROWN-UPS</p><h2>{creating?"Make a parent PIN":"Parent check"}</h2><p>{creating?"This keeps detailed history and settings tucked away.":"Enter your PIN to see family details."}</p><input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,8))} type="password" inputMode="numeric" autoComplete="current-password" aria-label="Parent PIN" placeholder="••••"/><button className="primary wide" onClick={submit}>{creating?"Create PIN":"Open grown-ups’ corner"}</button>{error&&<p className="error" role="alert">{error}</p>}<small>Face ID can be added here in a future update.</small></section>}

function Parent({checkIns,setCheckIns,notes,setNotes,settings,setSettings,tries,poos,streak,onLock}:{checkIns:CheckIn[];setCheckIns:(items:CheckIn[])=>void;notes:DayNote[];setNotes:(items:DayNote[])=>void;settings:Settings;setSettings:(s:Settings)=>void;tries:number;poos:number;streak:number;onLock:()=>void}){
 const[email,setEmail]=useState(settings.parentEmail||""),[password,setPassword]=useState(""),[status,setStatus]=useState(syncConfigured?"Family session connected":"Local demo mode"),[noteDate,setNoteDate]=useState(dateKey()),[noteText,setNoteText]=useState(notes.find(n=>n.date===dateKey())?.text||"");
 const recent30=checkIns.filter(c=>{const age=(Date.now()-new Date(c.date+"T12:00:00").getTime())/86400000;return age>=0&&age<30}),successful=recent30.filter(c=>c.outcome==="happy"||c.outcome==="neutral"),sizeCounts=sizes.map(s=>({label:s.label,count:successful.filter(c=>c.size===s.id).length})),maxSize=Math.max(1,...sizeCounts.map(s=>s.count)),activeDays=new Set(recent30.map(c=>c.date)).size;
 const saveNote=()=>{const note={date:noteDate,text:noteText.trim(),updatedAt:new Date().toISOString()};const next=[...notes.filter(n=>n.date!==noteDate),note];setNotes(next);syncDayNote(note).then(()=>setStatus("Parent note saved ✓")).catch(()=>setStatus("Note saved on this phone"))};
 const chooseNoteDate=(date:string)=>{setNoteDate(date);setNoteText(notes.find(n=>n.date===date)?.text||"")};
 const removeItem=(item:CheckIn)=>{if(!window.confirm("Delete this toilet-time record?"))return;setCheckIns(checkIns.filter(c=>c.id!==item.id));deleteCheckIn(item.id).then(()=>setStatus("Record deleted ✓")).catch(()=>setStatus("Deleted on this phone"))};
 const signIn=async()=>{if(!supabase)return;setStatus("Connecting…");const{error}=await supabase.auth.signInWithPassword({email,password});if(error)return setStatus(error.message);setSettings({...settings,parentEmail:email});await syncCheckIns(checkIns);setStatus("Family data synced ✓")};
 return <section className="page parent-page"><div className="parent-actions"><p>Private family view</p><button onClick={onLock}>Lock 🔒</button></div><div className="summary-grid"><div><span>⭐</span><strong>{tries}</strong><small>brave tries</small></div><div><span>🌈</span><strong>{poos}</strong><small>poo wins</small></div><div><span>🔥</span><strong>{streak}</strong><small>day rhythm</small></div></div>
 <div className="settings-card stats-card"><p className="eyebrow">LAST 30 DAYS</p><h3>A gentle look at the rhythm</h3><div className="stat-line"><strong>{activeDays}</strong><span>days with a toilet try</span></div><div className="stat-line"><strong>{successful.length}</strong><span>poo wins</span></div><h4>Recorded sizes</h4>{sizeCounts.map(s=><div className="size-stat" key={s.label}><span>{s.label}</span><i><b style={{width:`${s.count/maxSize*100}%`}}/></i><strong>{s.count}</strong></div>)}<small>Only check-ins with a recorded size are shown.</small></div>
 <div className="settings-card note-card"><h3>Parent day note</h3><p>Capture what made a day easier or harder for later reflection.</p><input type="date" max={dateKey()} value={noteDate} onChange={e=>chooseNoteDate(e.target.value)}/><textarea value={noteText} onChange={e=>setNoteText(e.target.value)} placeholder="For example: travel day, seemed uncomfortable, extra water helped…"/><button className="primary wide" onClick={saveNote}>Save parent note</button></div>
 <div className="settings-card"><h3>Family backup</h3><p>Download a private copy any time. It stays on this device unless you choose where to save it.</p><button className="secondary" onClick={()=>exportData(checkIns,notes)}>↓ Export family data</button></div><div className="settings-card"><h3>Secure family sync</h3><p className="sync-status"><i className={syncConfigured?"online":""}/>{status}</p>{!syncConfigured&&<p>Add the private Supabase settings during setup to turn on encrypted family sync.</p>}{syncConfigured&&!settings.parentEmail&&<><label>Parent email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary wide" onClick={signIn}>Sign in & sync</button></>}</div>
 <div className="settings-card history"><h3>History & corrections</h3>{checkIns.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(c=><div key={c.id}><span>{c.outcome==="not-yet"?"😌":c.outcome?"😊":"⭐"}</span><p><strong>{routines.find(r=>r.id===c.routine)?.label}</strong><small>{new Date(c.date+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})} · {c.outcome==="not-yet"?"brave try":"little win"}{c.size?` · ${c.size}`:""}</small></p><button className="delete-record" onClick={()=>removeItem(c)} aria-label={`Delete ${c.date} ${c.routine} record`}>Delete</button></div>)}</div></section>
}
