export type RoutineId = "breakfast" | "lunch" | "dinner";
export type Outcome = "happy" | "neutral" | "not-yet";
export type Size = "little" | "medium" | "big";
export type CheckIn = { id:string; date:string; routine:RoutineId; outcome?:Outcome; size?:Size; createdAt:string; updatedAt:string; synced?:boolean };
export type DayNote = { date:string; text:string; updatedAt:string };
export type MedicineMoment = "morning" | "evening";
export type MedicineCheckIn = { id:string; date:string; moment:MedicineMoment; createdAt:string; updatedAt:string; synced?:boolean };
export type WaterDay = { date:string; count:number; updatedAt:string };
export type Settings = { pinHash?:string; parentEmail?:string; waterTargetMl?:number };
